### PR TITLE
Add dev guide for 1PC

### LINKED ISSUE #118: Write down the first version of 1PC
https://github.com/pingcap/tidb-dev-guide/blob/master/src/understand-tidb/1pc.md
cc @MyonKeminta @tisonkun

### PR DESCRIPTION
**Pull request by MyonKeminta**
### What issue does this PR solve?

- close #118

### What is changed:

Added dev guide article for 1PC.

### CODE REVIEW

**Comment by cfzjywxk** [comment]
I like the way @MyonKeminta writting document :heart_eyes:

**Comment by MyonKeminta** [comment]
> I like the way @MyonKeminta writting document 😍

😂 I actually feel it very hard to organize proper words for this article...

**Comment by zhangyangyu** [comment]
@cfzjywxk @MyonKeminta ping

**Comment by MyonKeminta** [comment]
@cfzjywxk @cfzjywxk PTAL, thanks

**Review by sticnarf — APPROVED** [review]
LGTM

**Comment by cfzjywxk** [comment]
LGTM

**Comment by zhangyangyu** [comment]
Thanks everyone!

**Comment by zhangyangyu** [comment]
@all-contributors please add @MyonKeminta for content

**Pull request merged**
