### PR TITLE
Get started: update outdated command of running tests

### PR DESCRIPTION
**Pull request by Octobug**
### What issue does this PR solve?

- close: none of the existing issues is relative to this PR.

### What is changed:

The `gotest` makefile target was removed by pingcap/tidb#36530 due to issue pingcap/tidb#36493. This PR:

- Updated those commands in this doc: https://pingcap.github.io/tidb-dev-guide/get-started/write-and-run-unit-tests.html#running-all-tests
- Fixed a typo

### CODE REVIEW

**Comment by zhangyangyu** [comment]
@hawkingrei could you take a look? Seems similar to your #223

**Comment by Octobug** [comment]
> @hawkingrei could you take a look? Seems similar to your #223

It is similar to #223 . #223 has a `ci:` subject and a ❌ CI status, so I just took a glance at it and didn't check it out yesterday. = =

**Comment by hawkingrei** [comment]
@tiancaiamao PTAL

**Comment by Octobug** [comment]
This PR is getting stale, do I need to update anything?

**Pull request merged**
