### PR TITLE
add dql

### LINKED ISSUE #87: Write down the first version of DQL section

### PR DESCRIPTION
**Pull request by zhangyangyu**
### What issue does this PR solve?

- close #149 
- close #87 

### What is changed:

Add first version of DQL description. The original content is written by @mengxin9014 in #149 in Chinese. This is a translated version.

### CODE REVIEW

**Comment by mengxin9014** [comment]
others LGTM.

**Comment by zhangyangyu** [comment]
Thanks @xxchan for your comment. I've fixed them.

**Comment by zhangyangyu** [comment]
@tisonkun thanks for your review. I've addressed the comments.

**Comment by zhangyangyu** [comment]
@all-contributors please add @mengxin9014 for content

**Comment by zhangyangyu** [comment]
@all-contributors please add @mengxin9014 for content

**Pull request merged**
